Add creator attribute for data points
CenterForDigitalHumanities/geolocator pull request #50
Opened 2023-09-18 01:52 UTC by em-henken

There is still a bug, which I will need to look into. Only saves creator if first button is clicked on the URI input screen. However, if you wait to enter it after the first button but before "Confirm URI" button, it saves as an empty string. How to get it saved just based on the Confirm URI button, the last button clicked before going to the next window.

2023-09-18 21:36 UTC, tobradovic commented on public/components/layout.js
> +                localStorage.setItem("userResource", JSON.stringify({"@id":target, "creator":objCreator.value}))
So this is adding a new `creator` JSON object within the `userResource` JSON object, right?

2023-09-24 21:12 UTC, yashaswini-slu requested changes
Add the "Name and Email" in <label> tag and keep both label and input tag inside div tag

2023-09-24 21:32 UTC, yashaswini-slu requested changes
The creator JSON should not be added to JSON when there is no value provided

2023-09-25 15:06 UTC, thehabes requested changes

2023-09-25 15:06 UTC, thehabes commented on public/components/layout.js
> +                localStorage.setItem("userResource", JSON.stringify({"@id":target, "creator":objCreator.value}))
Do not add the `creator` key if the value is an empty string, `undefined`, or `null`

2023-09-25 15:06 UTC, thehabes commented on public/components/layout.js
> +                    "creator": userObj["creator"],
Make sure not to add the `creato`r key if the value is an empty string, undefined, or null

2023-09-25 19:57 UTC, yashaswini-slu requested changes
Name and URI should be in same div it should not be in different div's

2023-09-25 20:38 UTC, thehabes commented
I agree, we want it to look more like

![image](https://github.com/CenterForDigitalHumanities/geolocator/assets/3287006/834a26e7-18d4-4c5f-8302-bbea84055001)

Also, that message is a bit technically direct.  I love it, but I am not your typical user.  How about something along the lines of
```
Supply an existing Web Resource URI.  You also have the option to provide a name or E-mail to serve as the creator of this resource.  Use your own name or E-mail to take ownership of the data created!
```

`Use This URI` as the button text should probably also change, since now there is additional input.  Something more generic like  `Save and Next Step` or whatever you come up with.

2023-09-25 20:46 UTC, thehabes approved these changes
There it is!  Looks good, I think we will continually think about how to do the UI.  Still, it feels normal to me to provide my name and resource at the same time, and the button queues tie it all together.

2023-09-26 19:03 UTC, yashaswini-slu approved these changes
All changes are implemented.

2023-09-26 19:04 UTC, merged