Fix: download to local machine, issue #33
CenterForDigitalHumanities/geolocator pull request #52
Opened 2023-10-02 04:51 UTC by em-henken

<img width="1385" alt="Screenshot 2023-10-01 at 11 49 24 PM" src="https://github.com/CenterForDigitalHumanities/geolocator/assets/118228404/be7c94d0-3ef8-4ae1-ae16-275cc793eeb2">

button not functioning yet, will get that done before end of sprint.

2023-10-02 16:05 UTC, em-henken commented
Check is failing: "rerum geolocator site deploy".

2023-10-02 16:20 UTC, thehabes commented
@CenterForDigitalHumanities/geolocator-oss-devs sorry about the deploy failure!  It's on our end, we will have it fixed shortly.

2023-10-03 19:03 UTC, yashaswini-slu reviewed
Change button to icon

2023-10-07 16:45 UTC, thehabes requested changes
You have an error in the console

![image](https://github.com/CenterForDigitalHumanities/geolocator/assets/3287006/547d2129-7bcc-4944-88ba-a2028c894845)

I am definitely knit-picking with this one.  When I open the file in my code editor, it is all on one line and ultimately unreadable.  Is there any way you can get it to save `prettified`?

Outcome now
![image](https://github.com/CenterForDigitalHumanities/geolocator/assets/3287006/00595ec2-9ac6-4f6f-80d4-91b652610491)

Desired Outcome
![image](https://github.com/CenterForDigitalHumanities/geolocator/assets/3287006/6e026d25-3930-41d0-980e-7ccecee5998b)

2023-10-07 22:13 UTC, em-henken commented
requested changes have been made

2023-10-09 04:16 UTC, yashaswini-slu approved these changes

2023-10-09 15:55 UTC, thehabes approved these changes
Awesome, thanks for addressing those concerns.  Looks and functions exactly as I would expect.

2023-10-09 17:49 UTC, merged