Fix context: 3 appearing in JSON.
CenterForDigitalHumanities/geolocator pull request #55
Opened 2023-10-16 01:53 UTC by tobradovic

This bug was appearing because of unshift and shift functions being misused. `@context` was being set as the result of `unshift()` and `shift()` functions. These functions return the length of the item being modified, so that's why `@context` would appear as a number. The functions have been removed and reimplemented. Additionally, the ordering of the URIs in the `@context` are made to appear in the required order.

NOTE 1: Objects that have the api/2 or earlier keep that context and the api/3 and navPlace contexts are appended as always. This may be the intended functionality or a bug, waiting for feedback.

NOTE 2: URIs with `http` are considered different than URIs with `https`. This is pertinent in the case where `http://.../3/context.json` is appended to the context even if `https://.../3/context.json` is present. This may be the intended functionality or a bug, waiting for feedback.

2023-10-18 23:11 UTC, tobradovic commented
Ignore NOTE 2 in the first comment on the merge request. That was a flaw in my original implementation and no longer needs to be considered.

2023-10-22 00:09 UTC, yashaswini-slu requested changes
You can create a separate function to find if the context contains variations and use it for both the uri1 and uri2, no need to repeat the same code twice.

2023-10-22 20:11 UTC, yashaswini-slu approved these changes

2023-10-23 16:42 UTC, thehabes requested changes
There was a failure when testing.

Taking the object https://store.rerum.io/v1/id/11111 and the string "abc" all the way through the `annotate.html` flow produced a bad object.

```JSON
{
	"@context": [
		null,
		"http://www.w3.org/ns/anno.jsonld",
		"http://geojson.org/geojson-ld/geojson-context.jsonld"
	],
	"type": "Annotation",
	"motivation": "tagging",
	"body": {
		"type": "Feature",
		"geometry": {
			"type": "Point",
			"coordinates": [
				-106.347656,
				41.426253
			]
		},
		"properties": {}
	},
	"target": "abc"
}
```

2023-10-23 20:00 UTC, thehabes approved these changes
Tested and could not cause any errors.

Perhaps a little overthinking/overcoding here.  Since you have control over the context Array, you could build it in any order you want and wouldn't need to do switchPositions().  It is good to have thought about consistency and I am OK with this code moving forward.

2023-10-23 20:23 UTC, merged