Update landing page
CenterForDigitalHumanities/geolocator pull request #57
Opened 2023-10-16 20:57 UTC by em-henken

starting to recreate UI for landing page, site Nav, etc.

2023-10-22 00:16 UTC, yashaswini-slu requested changes
Keep the button after the text, as the heading and button have same text, its confusing to the user

2023-10-22 00:19 UTC, yashaswini-slu requested changes
Can you add some more look and feel for the page, like some border both the option, something like this:
<img width="573" alt="Screenshot 2023-10-21 at 19 18 50" src="https://github.com/CenterForDigitalHumanities/geolocator/assets/113057349/dc503c70-2619-4925-8f6c-a794eedc1f9b">
This is just an idea, you can think over it

2023-10-23 16:54 UTC, thehabes requested changes

2023-10-23 16:54 UTC, thehabes commented on public/index.html
> +                    Here you can enhance any <a target="_blank" href="https://www.w3.org/standards/semanticweb/data.html">Linked Open Data</a> resource by providing geospatial descriptors. This does
Sneak in the plug for RERUM here.

> You are able to attribute the data created here to yourself.  At the end, you can download your object as a JSON file or save it to RERUM as real usable linked data.

2023-10-23 16:54 UTC, thehabes commented on public/index.html
> +                <br></br>
If you can avoid it, don't use `<br>`

2023-10-23 16:54 UTC, thehabes commented on public/index.html
>                  <p>
This `<p>` doesn't close!  When you close it, you can give it a padding or margin to get the spacing effect you are going for (this is in relation to the `br` comment).

2023-10-23 16:54 UTC, thehabes commented on public/index.html
>                  <p>
This <p> doesn't close! When you close it, you can give it a padding or margin to get the spacing effect you are going for (this is in relation to the br comment).

2023-10-23 16:54 UTC, thehabes commented on public/index.html
> +                <br></br>
If you can avoid it, don't use <br>

2023-10-23 20:07 UTC, thehabes approved these changes
There is inline CSS all over the place here.  CSS should be applied via /stylesheets/style.css or by using existing Chota classes.  Either class your objects and create new CSS rules or take over the existing CSS rules.  It's OK for today, you can make this change during your next sprint.  I understand some of the inline CSS was already there.  Someone should have yelled at the developer that did that.

2023-10-23 20:22 UTC, yashaswini-slu approved these changes

2023-10-23 20:23 UTC, merged