WIP: issue #28 code highlighting
CenterForDigitalHumanities/geolocator pull request #73
Opened 2024-02-03 23:13 UTC by em-henken

found library and it edits the json. However it is all red and not really doing anything useful so I will gave to look how to get the library to give better results or choose a new library. WIP

2024-02-08 20:52 UTC, em-henken commented
chose a different library, https://www.npmjs.com/package/json-format-highlight. Works well, ready for review

2024-02-09 19:30 UTC, thehabes requested changes
This is perfect, I like the way the library looks.

I would like to see this same library used on #takeout.  This is the area showing the object after saving it into RERUM, seen below.

![image](https://github.com/CenterForDigitalHumanities/geolocator/assets/3287006/f7c3949e-cf71-4332-be19-945328658844)

You will notice this area being set like
```javascript
takeout.innerHTML = JSON.stringify(createdResource, null, '\t')
```
so it should be fairly simple to upgrade it to the new code highlighting style.

2024-02-12 18:04 UTC, yashaswini-slu approved these changes

2024-02-12 22:58 UTC, thehabes approved these changes
There it is!  Good change.  I notice it does not have a download button, but that kind of works because at this point they should be taking the URL.

![image](https://github.com/CenterForDigitalHumanities/geolocator/assets/3287006/4454cf71-438e-4cc0-9042-064c09461e6e)

2024-02-15 18:56 UTC, merged