Using Media Queries
CenterForDigitalHumanities/geolocator pull request #75
Opened 2024-02-19 18:54 UTC by kmcmakin00

I am planning on using Media Queries that change the layout depending on screen size.

2024-02-25 22:10 UTC, yashaswini-slu requested changes
i can still see the same design for the footer
<img width="696" alt="Screenshot 2024-02-25 at 16 08 25" src="https://github.com/CenterForDigitalHumanities/geolocator/assets/113057349/a3c5aff5-1d55-4871-873e-b1e8d06b8857">

2024-03-18 16:14 UTC, yashaswini-slu requested changes
<img width="1434" alt="Screenshot 2024-03-18 at 11 11 55" src="https://github.com/CenterForDigitalHumanities/geolocator/assets/113057349/5e2cef7b-8639-4315-bf13-d9a33fa274c4">
we can improve this design

2024-03-18 16:15 UTC, yashaswini-slu requested changes
we can add tooltip - helper text, user will get an idea of what that icon is for.
<img width="1438" alt="Screenshot 2024-03-18 at 11 14 38" src="https://github.com/CenterForDigitalHumanities/geolocator/assets/113057349/76160fcb-0bc4-4c23-8d54-c64e7817e4de">

2024-05-05 18:03 UTC, yashaswini-slu requested changes
Update the branch with main branch

2024-05-07 18:50 UTC, thehabes requested changes
I do see a great deal of improvement in how the header/footer is handle as I move between device emulators, this is much better.  I am impressed that both landscape and portrait mode were taken into account.

I can see the footer icons just did not want to line up for you in some cases.  [Using a "grid" technique](https://jenil.github.io/chota/#grid) may help this be more consistent.  Remember that you have Chota CSS in the background, and using the `row` and `column` classes can do a lot of this as well.  It is OK as-is, just leaving this note.

**Galaxy S20+**
![image](https://github.com/CenterForDigitalHumanities/geolocator/assets/3287006/501b3094-ea3a-4bca-83e4-d570c8f87733)

**Galaxy S8**
![image](https://github.com/CenterForDigitalHumanities/geolocator/assets/3287006/8f92a9f3-3bbe-4fe3-9660-d6021b23afe1)

I notice a lot of whitespace changes where the tab index has been changed that should be cleaned up.  If you look at your diff, then apply the "hide whitespace changes" settings and see it again, you'll see how much "unchanged" code is affected (it is significant).

![image](https://github.com/CenterForDigitalHumanities/geolocator/assets/3287006/10a9c04f-f767-4556-93a2-d02fe077e69e)

**Make sure to resolve the conflicts** (I think the whitespace is involved here.)  I have noted some links to update and some cleanup items inline.  Just some cleanup stuff to think about polishing this up before taking it forward.

2024-05-07 18:50 UTC, thehabes commented on public/components/layout.js
> +		<small class = "tooltiptext">&copy;2022 Research Computing Group</small></a>
&copy;**2024** Research Computing Group

2024-05-07 18:50 UTC, thehabes commented on public/components/layout.js
> +		<span class= "tooltiptext">SLU Research Group</span></a>
Just "SLU Research"

2024-05-07 18:50 UTC, thehabes commented on public/components/layout.js
> +	<a target="_blank" class= "tooltip"id = "rerum" href="http://rerum.io">
Also not your fault.  Finally got our act together and have https

`href="https://rerum.io"`

2024-05-07 18:50 UTC, thehabes commented on public/components/layout.js
> +	constructor(){
Try to `undiff` whitespace changes like this if you didn't change the code.  Changing the whitespace can have consequences, some bracket-less languages really care about this and it is a bad habit to form.

2024-05-07 18:50 UTC, thehabes commented on public/stylesheets/style.css
> +	bottom : 0;
Try to `undiff` whitespace changes like this if you didn't change the code.  Changing the whitespace can have consequences, some bracket-less languages really care about this and it is a bad habit to form.

2024-05-16 21:52 UTC, closed without merging